name: Nuget Package Deploy

on: 
 push:
   branches: 
     - master
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2     
    - name: Build with dotnet
      run: dotnet msbuild -property:Configuration=Release
    - name: Push Package to nuget
      run: dotnet nuget push **/*.nugpkg
             --api-key ${{ secrets.nugetapikey }}
             --source https://api.nuget.org/v3/index.json
